name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Shortly.sln
    - name: Build
      run: dotnet build ./src/Shortly.sln -c Release --no-restore
    - name: Test
      run: dotnet test ./src/Shortly.sln --no-build --verbosity normal
